#!/bin/bash

latest_backup=$(find $HOME -maxdepth 1 -type d -name "Backup-*" -mtime -7 -print | sort -r | head -n 1)
if [[ ! -z "$latest_backup" ]]; then
	mkdir -p "$HOME/restore"
	find $latest_backup -type f ! -regex ".[0-9]{4}-[0-9]{2}-[0-9]{2}" -exec cp {} "$HOME/restore/" \; 
else
	echo "no Backup dirs were found"
fi
